### ISSUE TITLE
Error while migrating files

### ISSUE THREAD

**Issue by 0gener** [directus-community/migration-tool#16]
Hey guys!

I'm getting an error when the migration tool reaches the Uploading Files task.
```
TypeError: Cannot read property 'split' of undefined
    at Task.task (file:///.../migration-tool/tasks/files.js:62:32)
```
Looking at the code, it's trying to split the string using the property `data.asset_url` that doesn't exist in the [File Object](https://v8.docs.directus.io/api/files.html#the-file-object). Shouldn't it be using the property `data.full_url` instead?

**Comment by totev** [comment]
Seems like the problem is still there: #29

**Comment by rijkvanzanten** [comment]
@totev Wanna open a PR for it?
