### ISSUE TITLE
Choices lost during migration

### ISSUE THREAD

**Issue by th3noname** [directus-community/migration-tool#20]
I have collections that feature muliple choice state selection, as seen in the V8 screenshots. The migration completed successfully but the choices are lost.

**V8**
Edit item:
![grafik](https://user-images.githubusercontent.com/1923981/114379406-103a1980-9b89-11eb-9683-991f94c00dad.png)
Field configuration:
![grafik](https://user-images.githubusercontent.com/1923981/114379482-2942ca80-9b89-11eb-9aad-26aa66384061.png)

**V9**
Edit item:
![grafik](https://user-images.githubusercontent.com/1923981/114379526-365fb980-9b89-11eb-9247-be5932197459.png)
Field configuration:
![grafik](https://user-images.githubusercontent.com/1923981/114379590-46779900-9b89-11eb-91ec-2e3a66b654ec.png)

**Comment by rijkvanzanten** [comment]
Interface options aren't copied over right now, as the structure/names have changed quite a bit. Migrating over those choices would be really useful though! @th3noname wanna open a PR for that?
