### ISSUE TITLE
Migration fails with only a single user in the v8 database

### ISSUE THREAD

**Issue by cdanny358** [directus-community/migration-tool#21]
With only a single source user, migration fails at `tasks/user.js`, line 92:

`context.userMap[user.id] = createdUsers.data.data[index].id;`

Upon investigation it seems that `createdUsers.data.data` is an object rather than an array with a single user. I fixed it by changing line 92 to this: 

`context.userMap[user.id] = createdUsersAsArray[index].id;`

`createdUsersAsArray` is defined but never used, and I assume this to be its purpose.
Line 95 may require the same substitution, although it completed the migration without changing it.

**Comment by rijkvanzanten** [comment]
@cdanny358 Wanna open this as a PR?:

> Upon investigation it seems that createdUsers.data.data is an object rather than an array with a single user. I fixed it by changing line 92 to this:

🙂
