### ISSUE TITLE
"Bad Request" Error on migrating relations

### ISSUE THREAD

**Issue by Zax-code** [directus-community/migration-tool#31]
The creation of collections seems to be working fine but when it comes to migrating relations I get this message

migration tool side:
![image](https://user-images.githubusercontent.com/67737332/121337908-4c85be00-c91d-11eb-81bf-99e8fec158cd.png)

v9 directus project side:
![image](https://user-images.githubusercontent.com/67737332/121337242-9fab4100-c91c-11eb-98bb-8d492e6e3b42.png)

I have noticed that the data sent wasn't in the same format as the users_relations' table of my v9 directus :
sent data :
![image](https://user-images.githubusercontent.com/67737332/121337492-e1d48280-c91c-11eb-9c69-a81b0bda31e2.png)

directus_relations of my v9 directus database:
![image](https://user-images.githubusercontent.com/67737332/121337645-0b8da980-c91d-11eb-91dd-4921584afd58.png)

As you can see there is no 'id' key, 'sort_field' key nor 'one_deselect_action' key in the sent data (the same goes for all the other elements in the array, they're all in the same format)
Is it related to my issue ? Anyway, how can I fix this ?
Thanks in advance.

**Comment by hakan-erdem-temiz** [comment]
<cmd-e>
  const mappedRelations = [...relationsV9, ...systemFields].map( realtion => {
    return {
      meta: realtion,
      field: realtion.many_field,
      collection: realtion.many_collection,
    }
  } );

try {
  await Promise.allSettled(mappedRelations.map( async (relation) => await apiV9.post("/relations",relation)));
} catch (err) {
  console.log(err)
}
<cmd-e>

Hi Zax, I noticed this issue too. In the API reference it says that the endpoint only accepts the object, therefore this kind of mapping can work for you.
 
 https://docs.directus.io/reference/api/system/revisions/

**Comment by rijkvanzanten** [comment]
@hakan-erdem-temiz Wanna open a PR for that?

**Comment by hakan-erdem-temiz** [comment]
Hi @rijkvanzanten, thanks. I would like to.

**Comment by Zax-code** [comment]
Hi, thanks for your reply and your fix ! It appears to have worked, however it didn't migrate all the fields in each collection, some collection miss several fields. I don't know if it's your solution that skipped them or just the original migration script but anyway thank you very much for your reply ! Shall I close the issue now ?

**Comment by hakan-erdem-temiz** [comment]
Hi @Zax-code , you're welcome. I've updated the fix but for your case you might consider editing the filter. I made some custom solutions for my code but I published the most general one. Have fun.

```
    .filter((relation) => {
      return (
        (relation.collection_many.startsWith("directus_") &&
          relation.collection_one.startsWith("directus_")) === false
      );
    })
```

**Comment by william-roy** [comment]
+1 
I'm having the same issue, the schemas migrate just fine, but it fails as soon as it tries to copy the collection items themselves.

`> Migrating Schema
    √ Downloading Schema
    > Creating Collections
      × alerts
        → Request failed with status code 400`
