### ISSUE TITLE
Crash when migrating users database 

### ISSUE THREAD

**Issue by jroxendal** [directus-community/migration-tool#5]
Stupidly, I initiated a new database in directus 9 using the same admin email address as my admin user in directus 8. That resulted in a crash without an understandable error message (Error 400) when attempting to migrate the user database. This might need documentation or a quick preflight check before running migration.

**Comment by weyrloc** [comment]
Hello,
Check if one email in the old Directus is not already used in the new Directus.
I had one similar email and the miration tools crashed for that.
