### ISSUE TITLE
Migrating stops with Status field type.

### ISSUE THREAD

**Issue by richardt3** [directus-community/migration-tool#52]
Hi,

Using the latest code. V8 latest and V9 rc91. When I run the migration it stops on a collection with this error -
```    
 ✖ principal_projects
        → Cannot read property 'value' of undefined
```
and this stack trace at the end. It looks to be something related to an issue reading option.soft_delete values from a field of type Status. The status mappings all have soft delete in the off state. 26 collections are migrated before this one, so it's working up until then.

```
TypeError: Cannot read property 'value' of undefined
    at Task.task (file:///home/support/migration-tool/tasks/schema.js:168:53)
    at /home/support/migration-tool/node_modules/listr/lib/task.js:167:30
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5) {
  context: [Object: null prototype] {
    completedSteps: {
      schema: true,
      collections: false,
      files: false,
      roles: false,
      users: false,
      relationsv8: false,
      relations: false,
      data: false,
      completed: false
    },

```
We could possibly just delete the field and recreate on the migrated version, but wondered if there's something I else I can do?

Thanks

Richard

**Comment by ivanviskovic** [comment]
The problem here is if field `soft_delete` is false then the find will fail:

`archive_value: Object.values(
  statusField.options.status_mapping
).find((option) => option.soft_delete).value,`

**Comment by richardt3** [comment]
> The problem here is if all `soft_delete` fields are false then the find will fail and throw that error:
> 
> `archive_value: Object.values( statusField.options.status_mapping ).find((option) => option.soft_delete).value,`

So for now, I could just set one item to soft-delete and then set it back post-migration?

**Comment by ivanviskovic** [comment]
@richardt3  Yes, that would work. Not a nice way but it's something.

**Comment by richardt3** [comment]
> @richardt3 Yes, that would work. Not a nice way but it's something.

Thank you, it's a small alteration but will allow us to start testing the v9 Release Candidates :-)

**Comment by richardt3** [comment]
> @richardt3 Yes, that would work. Not a nice way but it's something.

Yes - that worked :-) but ran into another issue in migrating repeaters.

**Comment by ivanviskovic** [comment]
@richardt3 same here, too many issues in migration, so i just gave up and will remain on v8 until these problems are fixed.

**Comment by rijkvanzanten** [comment]
> so i just gave up and will remain on v8 until these problems are fixed.

Instead of waiting for somebody else, do you just wanna try fixing the issue yourself? It [sounds like you already found what went wrong](https://github.com/directus-community/migration-tool/issues/52#issuecomment-920786002). This is a community driven open source project after all 😄

**Comment by ivanviskovic** [comment]
@rijkvanzanten unfortunately we have rather complex data structure that revolves around directus (some things are not even supported in v9) and the migration would took too many manual work even with this tool. That's why i have decided to remain on v8 for some time.
And you are right i should contribute to this project.
Sorry if i sounded harsh at my previous comment, it was not my intention.

**Comment by kiwimonk** [comment]
> That's why i have decided to remain on v8 for some time.
Same here.  I just spent half my day trying to migrate.  This tool needs a lot of love.

**Comment by benhaynes** [comment]
> > That's why i have decided to remain on v8 for some time.
> > Same here.  I just spent half my day trying to migrate.  This tool needs a lot of love.

This is because there were enormous improvements (changes) to the codebase between major releases (primarily, that everything was completely rewritten from PHP to JavaScript)... so that's not our "normal" upgrade experience.

Apologies for the difficulty, but it's a hard to balance staying modern and avoiding structural/breaking changes.

❤️

**Comment by kiwimonk** [comment]
@benhaynes no doubt it is hard to balance all of the spinning plates.  Your move to a more modern stack is an incredibly welcomed and important one.  With version 9 going stable only a month ago, all hands have obviously been busy.
