### ISSUE TITLE
Datetimepicker fields in v8 cannot be imported into v9

### ISSUE THREAD

**Issue by moekify** [directus-community/migration-tool#54]
**Problem**
If you have a V8 instance with a MYSQL-DB, it seems that the datetime picker interface in V8 gets saved as a non ISO timestamp, that isn't compatible with the v9 import endpoint, that expects iso formatted timestamps.

This doesn't seem to have timezone information either. Which really makes this annoying :D!

Looks like the datetime field implementation has no concept of i18n. 
https://github.com/directus/v8-archive/blob/681196fead1f87e2f73d2cdf64af34543d3140cf/app/src/interfaces/datetime/input.vue

vs 
https://github.com/directus/v8-archive/blob/681196fead1f87e2f73d2cdf64af34543d3140cf/app/src/interfaces/datetime-created/input.vue#L21

Related PR that killed the "it works still": https://github.com/directus/directus/pull/7200

**Comment by moekify** [comment]
@rijkvanzanten I'm unsure how to approach trying to fix this. This kinda seems like it should be fixed in v8? :D 

Alternatively, we could maaaybe try to convert all these dates inside the migration based on timezone in the settings of the v8 instance? 

WDYT?

**Comment by rijkvanzanten** [comment]
> Alternatively, we could maaaybe try to convert all these dates inside the migration based on timezone in the settings of the v8 instance?

Odd! I thought v8's date would be returned as `yyyy-mm-dd`, which should be allowed as iso8601 as well 🤔

**Comment by rijkvanzanten** [comment]
Ohh datetime in v8 might be "mysql format"! Yeah we should convert that to ISO8601, without the TZ information. The datetime field in v8 didn't do anything with timezones, nor does the datetime field in v9, so that should be a conversion we should be able to do in the migrations tool

**Comment by moekify** [comment]
I unfortunately only a V8 instance that runs in prod, so can't experiment much. Do you have an easy way to try reproduce that this isn't just something pertaining to my v8 instance?

**Comment by rijkvanzanten** [comment]
> Do you have an easy way to try reproduce that this isn't just something pertaining to my v8 instance?|

That's a very good question, I don't really have anything v8 running anymore locally 👀 We might be able to use the latest published tag of v8 on docker?

**Comment by moekify** [comment]
@rijkvanzanten https://github.com/directus-community/migration-tool/pull/55 Should fix this I presume

**Comment by rijkvanzanten** [comment]
Thanks!
