### ISSUE TITLE
Incorrect default value for v8 array type fields

### ISSUE THREAD

**Issue by miguelsimoes** [directus-community/migration-tool#9]
When migrating a schema from v8 that is defined as an array and contains a default value, the creation of the table on v9 fails complaining that the default value is not a valid JSON.

Example field definition to reproduce:
`"field_name": {
         "field": "field_name",
         "datatype": "VARCHAR",
         "type": "array",
         "sort": 2300,
         "interface": "multiselect",
         "required": true,
         "default_value": "some_option1",
         "options": {
            "choices": {
               "some_option1": "some_option1",
               "some_option2": "some_option2",
               "some_option3": "some_option3",
               "some_option4": "some_option4",
            },
            "allow_other": false,
            "draggable": false,
            "wrap": false,
            "formatting": true,
            "single": false
         },
         "locked": 0,
         "width": "full",
         "length": "255"
      },`

**Comment by rijkvanzanten** [comment]
Fixed in #14
